apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubeshark-tls
  namespace: default
spec:
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: cert-kubeshark
  dnsNames:
  - ks.svc.cluster.local
